version: 0.2

env:
  variables:
    FRONTEND_BUCKET: "findlove"

phases:
  build:
    commands:
      - echo "Deploying From Source"
      - pwd
      - ls
      - printenv

  lambdas:
    on-failure: CONTINUE
    commands:
      - echo "Deploying lambdas"
      - cd lambdas
      - |
      for file in LF-*.py; do
        name=$(basename "$file" .py)
        cp $file lambda_function.py
        zip ${name}.zip lambda_function.py
        if aws lambda update-function-code --function-name $name --zip-file fileb://${name}.zip; then
          echo "Successfully deployed ${name}"
        else
          echo "Failed to deploy ${name}"
        fi
      done
      - cd ..

  frontend:
    on-failure: CONTINUE
    commands:
      - echo "Deploying Frontend..."
      - cd frontend
      - aws s3 sync . s3://${FRONTEND_BUCKET} --delete
      - cd ..
