version: 0.2

env:
  variables:
    FRONTEND_BUCKET: "findlove"

phases:
  pre_build:
    commands:
      - pwd
      - ls
      - printenv

  build:
    commands:
      - echo "Deploying Lambdas..."
      - cd lambdas
      - |
        for lambda in ./*/; do
          if [[ -d "$lambda" ]]; then
            cd $lambda
            zip ${lambda}.zip *
            if aws lambda update-function-code --function-name $lambda --zip-file fileb://${lambda}.zip; then
              echo "Successfully deployed ${lambda}"
            else
              echo "Failed to deploy ${lambda}"
            fi
          fi
        done
      - cd ..
