version: 0.2

phases:
  build:
    commands:
      - pwd
      - for file in LF-*.py; do
          name=$(basename "$file" .py)
          # Deploy the lambda
          cp $file lambda_function.py
          zip ${name}.zip lambda_function.py
          if aws lambda update-function-code --function-name $name --zip-file fileb://${name}.zip; then
            echo "Successfully deployed ${name}"
          else
            echo "Failed to deploy ${name}"
          fi
        done